server:
  port: 80
eureka:
  client:
    register-with-eureka: false
    service-url:
      #注册中心集群,集群3个机器
      defaultZone: http://eurekaserver9000.com:9000/eureka/,http://eurekaserver9001.com:9001/eureka/,http://eurekaserver9002.com:9002/eureka/

